-- Create the school_subscriptions table
CREATE TABLE IF NOT EXISTS school_subscriptions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    school_id VARCHAR(20) NOT NULL,
    subscription_type ENUM('termly', 'annually') NOT NULL,
    pricing_plan_id INT NOT NULL,
    subscription_start_date DATE NOT NULL,
    subscription_end_date DATE NOT NULL,
    current_term VARCHAR(50),
    academic_year VARCHAR(20),
    active_students_count INT DEFAULT 0,
    cbt_stand_alone_enabled TINYINT(1) DEFAULT 0,
    sms_subscription_enabled TINYINT(1) DEFAULT 0,
    whatsapp_subscription_enabled TINYINT(1) DEFAULT 0,
    email_subscription_enabled TINYINT(1) DEFAULT 0,
    express_finance_enabled TINYINT(1) DEFAULT 0,
    base_cost DECIMAL(10, 2) NOT NULL,
    addon_cost DECIMAL(10, 2) NOT NULL DEFAULT 0,
    discount_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
    total_cost DECIMAL(10, 2) NOT NULL,
    payment_status ENUM('pending', 'paid', 'overdue', 'cancelled') DEFAULT 'pending',
    balance DECIMAL(10, 2) NOT NULL,
    status ENUM('active', 'inactive', 'expired', 'suspended') DEFAULT 'active',
    created_by VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (pricing_plan_id) REFERENCES subscription_pricing(id),
    INDEX idx_school_id (school_id),
    INDEX idx_subscription_type (subscription_type),
    INDEX idx_status (status),
    INDEX idx_subscription_dates (subscription_start_date, subscription_end_date)
);

-- Create the subscription_invoices table
CREATE TABLE IF NOT EXISTS subscription_invoices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    invoice_number VARCHAR(50) UNIQUE NOT NULL,
    school_id VARCHAR(20) NOT NULL,
    subscription_id INT NOT NULL,
    invoice_date DATE NOT NULL,
    due_date DATE NOT NULL,
    subtotal DECIMAL(10, 2) NOT NULL,
    discount DECIMAL(10, 2) NOT NULL DEFAULT 0,
    total_amount DECIMAL(10, 2) NOT NULL,
    payment_status ENUM('unpaid', 'paid', 'partial', 'overdue', 'cancelled') DEFAULT 'unpaid',
    balance DECIMAL(10, 2) NOT NULL,
    created_by VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (subscription_id) REFERENCES school_subscriptions(id) ON DELETE CASCADE,
    INDEX idx_school_id (school_id),
    INDEX idx_invoice_number (invoice_number),
    INDEX idx_payment_status (payment_status),
    INDEX idx_due_date (due_date)
);